### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by alexsprokosin** [xcoder-tool/XCoder#26]
[ERROR] An error has been caught in function 'main', process 'MainProcess' (4472), thread 'MainThread' (5660):
Traceback (most recent call last):

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\main.py", line 49, in <module>
    main()
    └ <function main at 0x000001A17056A340>

> File "C:\Users\GamePC\Desktop\XCoder-2.7.2\main.py", line 32, in main
    refill_menu()
    └ <function refill_menu at 0x000001A172B776A0>

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\main_menu.py", line 71, in refill_menu
    from system.lib.features.sc.decode import (

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\features\sc\decode.py", line 9, in <module>
    from system.lib.features.cut_sprites import render_objects

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\features\cut_sprites.py", line 7, in <module>
    from system.lib.objects.renderable.renderable_factory import (

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\objects\__init__.py", line 3, in <module>
    from system.lib.objects.texture import SWFTexture

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\objects\texture.py", line 15, in <module>
    from system.lib.pvr_tex_tool import get_image_from_ktx_data

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\pvr_tex_tool.py", line 30, in <module>
    _cli_path = _get_executable_path(_cli_name, f"{_main_dir}/system/bin/{_cli_name}")
                │                    │             │                      └ 'PVRTexToolCLI'
                │                    │             └ 'C:\\Users\\GamePC\\Desktop\\XCoder-2.7.2'
                │                    └ 'PVRTexToolCLI'
                └ <function _get_executable_path at 0x000001A172E0BB00>

  File "C:\Users\GamePC\Desktop\XCoder-2.7.2\system\lib\pvr_tex_tool.py", line 19, in _get_executable_path
    from distutils.spawn import find_executable

ModuleNotFoundError: No module named 'distutils'

**Comment by alexsprokosin** [comment]
как пофикить?

**Comment by danila-schelkov** [comment]
Исправлено в последнем релизе программы.
